"""create drug table

Revision ID: 33ec755a108a
Revises: add_medication_intake_log
Create Date: 2025-11-23 12:50:33.327245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33ec755a108a'
down_revision: Union[str, None] = 'add_medication_intake_log'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drug',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rx_cui', sa.String(), nullable=False),
    sa.Column('generic_name', sa.String(), nullable=False),
    sa.Column('brand_names', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drug_generic_name'), 'drug', ['generic_name'], unique=False)
    op.create_index(op.f('ix_drug_rx_cui'), 'drug', ['rx_cui'], unique=True)
    op.create_table('interaction_rule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('a_rx_cui', sa.String(), nullable=False),
    sa.Column('b_rx_cui', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('mechanism', sa.Text(), nullable=False),
    sa.Column('guidance', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_rule_a_rx_cui'), 'interaction_rule', ['a_rx_cui'], unique=False)
    op.create_index(op.f('ix_interaction_rule_b_rx_cui'), 'interaction_rule', ['b_rx_cui'], unique=False)
    op.add_column('label_chunk', sa.Column('chunk_text', sa.Text(), nullable=False))
    op.alter_column('label_chunk', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('label_chunk', 'rx_cui',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('label_chunk', 'section',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.drop_index(op.f('label_chunk_emb_idx'), table_name='label_chunk', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index(op.f('label_chunk_rx_cui_idx'), table_name='label_chunk')
    op.drop_index(op.f('label_chunk_section_idx'), table_name='label_chunk')
    op.create_index(op.f('ix_label_chunk_rx_cui'), 'label_chunk', ['rx_cui'], unique=False)
    op.drop_column('label_chunk', 'source_url')
    op.drop_column('label_chunk', 'created_at')
    op.drop_column('label_chunk', 'snippet')
    op.drop_column('label_chunk', 'emb')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('label_chunk', sa.Column('emb', sa.NullType(), autoincrement=False, nullable=False))
    op.add_column('label_chunk', sa.Column('snippet', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('label_chunk', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('label_chunk', sa.Column('source_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_label_chunk_rx_cui'), table_name='label_chunk')
    op.create_index(op.f('label_chunk_section_idx'), 'label_chunk', ['section'], unique=False)
    op.create_index(op.f('label_chunk_rx_cui_idx'), 'label_chunk', ['rx_cui'], unique=False)
    op.create_index(op.f('label_chunk_emb_idx'), 'label_chunk', ['emb'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.alter_column('label_chunk', 'section',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('label_chunk', 'rx_cui',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('label_chunk', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('label_chunk', 'chunk_text')
    op.drop_index(op.f('ix_interaction_rule_b_rx_cui'), table_name='interaction_rule')
    op.drop_index(op.f('ix_interaction_rule_a_rx_cui'), table_name='interaction_rule')
    op.drop_table('interaction_rule')
    op.drop_index(op.f('ix_drug_rx_cui'), table_name='drug')
    op.drop_index(op.f('ix_drug_generic_name'), table_name='drug')
    op.drop_table('drug')
    # ### end Alembic commands ###
