"""init tables

Revision ID: f39dd96ef116
Revises: 
Create Date: 2025-10-23 15:21:56.159979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f39dd96ef116'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drug',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rx_cui', sa.String(), nullable=False),
    sa.Column('generic_name', sa.String(), nullable=False),
    sa.Column('brand_names', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drug_generic_name'), 'drug', ['generic_name'], unique=False)
    op.create_index(op.f('ix_drug_rx_cui'), 'drug', ['rx_cui'], unique=True)
    op.create_table('interaction_rule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('a_rx_cui', sa.String(), nullable=False),
    sa.Column('b_rx_cui', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('mechanism', sa.Text(), nullable=False),
    sa.Column('guidance', sa.Text(), nullable=False),
    sa.Column('evidence_ids', postgresql.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_rule_a_rx_cui'), 'interaction_rule', ['a_rx_cui'], unique=False)
    op.create_index(op.f('ix_interaction_rule_b_rx_cui'), 'interaction_rule', ['b_rx_cui'], unique=False)
    op.create_table('label_chunk',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rx_cui', sa.String(), nullable=False),
    sa.Column('section', sa.String(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_label_chunk_rx_cui'), 'label_chunk', ['rx_cui'], unique=False)
    op.drop_table('tmp_embed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tmp_embed',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('emb', sa.NullType(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('tmp_embed_pkey'))
    )
    op.drop_index(op.f('ix_label_chunk_rx_cui'), table_name='label_chunk')
    op.drop_table('label_chunk')
    op.drop_index(op.f('ix_interaction_rule_b_rx_cui'), table_name='interaction_rule')
    op.drop_index(op.f('ix_interaction_rule_a_rx_cui'), table_name='interaction_rule')
    op.drop_table('interaction_rule')
    op.drop_index(op.f('ix_drug_rx_cui'), table_name='drug')
    op.drop_index(op.f('ix_drug_generic_name'), table_name='drug')
    op.drop_table('drug')
    # ### end Alembic commands ###
